apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: kafka-cluster
  name: kafka-cluster
spec:
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
    - name: "9093"
      port: 9093
      targetPort: 9093
  selector:
    io.kompose.service: kafka-cluster
