apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: scraper-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: scraper
  minReplicas: 1
  maxReplicas: 5 # Adjust this value based on your requirements
  targetCPUUtilizationPercentage: 50 # Adjust this value based on your CPU utilization threshold
