apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: scraper-gateway
  name: scraper-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: scraper-gateway
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: scraper-gateway
    spec:
      containers:
      - image: scraper-gateway
        imagePullPolicy: ""
        name: scraper-gateway
        ports:
        - containerPort: 4000
        resources: {}
        volumeMounts:
        - mountPath: /scraper-gateway
          name: scraper-gateway-claim0
      hostname: scraper-gateway
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: scraper-gateway-claim0
        persistentVolumeClaim:
          claimName: scraper-gateway-claim0
status: {}
