apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: scraper
  name: scraper
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: scraper
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: scraper
    spec:
      containers:
      - env:
        - name: DATABASE_HOST
          value: postgres
        - name: DATABASE_NAME
          value: scraper_db
        - name: DATABASE_PASSWORD
          value: supersecret
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_USERNAME
          value: scraper
        image: scraper
        imagePullPolicy: ""
        name: scraper
        ports:
        - containerPort: 6004
        resources: {}
        volumeMounts:
        - mountPath: /scraper
          name: scraper-claim0
      hostname: scraper
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: scraper-claim0
        persistentVolumeClaim:
          claimName: scraper-claim0
status: {}
